### ISSUE TITLE
error: use of undeclared identifier 'aligned_alloc'

### ISSUE THREAD

**Issue by BH1SCW** [fengbingchun/Messy_Test#1]
On Mac OS:

demo/CppBaseTest/cplusplus_secure_coding.cpp:439:25: error: use of undeclared identifier 'aligned_alloc'
        float* array = (float*)aligned_alloc(16, arr_size * sizeof(float));

**Comment by fengbingchun** [comment]
@BH1SCW 没有在Mac上试过，网上也有遇到类似的问题，如https://github.com/sumoprojects/sumokoin/issues/101 ，好像在Mac上需要使用posix_memalign替换aligned_alloc
