### ISSUE TITLE
Ubuntu上编译出错

### ISSUE THREAD

**Issue by HatakeKakaxi** [fengbingchun/Messy_Test#2]
博主你好，我尝试在Ubuntu18.04下编译linux_cmake_CppBaseTest，结果发现编译出错了，似乎是因为编译选项添加有问题，导致没有识别出C++11及以上版本，博主能否帮忙看一下？
这是错误信息：
/home/lhh/Documents/learning/coding/Messy_Test/demo/CppBaseTest/effective_modern_cplusplus.cpp: In member function ‘double effective_modern_cplusplus_::Point16::distanceFromOrigin() const’:
/home/lhh/Documents/learning/coding/Messy_Test/demo/CppBaseTest/effective_modern_cplusplus.cpp:633:15: error: ‘sqrt’ is not a member of ‘std’
   return std::sqrt((x*x) + (y*y));
               ^~~~
/home/lhh/Documents/learning/coding/Messy_Test/demo/CppBaseTest/effective_modern_cplusplus.cpp:633:15: note: suggested alternative: ‘sort’
   return std::sqrt((x*x) + (y*y));

/home/lhh/Documents/learning/coding/Messy_Test/demo/CppBaseTest/effective_modern_cplusplus.cpp: In function ‘int effective_modern_cplusplus_::test_item_32()’:
/home/lhh/Documents/learning/coding/Messy_Test/demo/CppBaseTest/effective_modern_cplusplus.cpp:1244:20: error: ‘bind’ is not a member of ‘std’
  auto func7 = std::bind([](const std::unique_ptr<Widget32>& pw) {return pw->isValidated() && pw->isArchived(); }, std::make_unique<Widget32>()); // C++11
                    ^~~~
/home/lhh/Documents/learning/coding/Messy_Test/demo/CppBaseTest/effective_modern_cplusplus.cpp:1244:20: note: suggested alternative: ‘find’
  auto func7 = std::bind([](const std::unique_ptr<Widget32>& pw) {return pw->isValidated() && pw->isArchived(); }, std::make_unique<Widget32>()); // C++11

**Comment by fengbingchun** [comment]
@HatakeKakaxi 我刚在Ubuntu 18.04上测试了可以正常编译。你试试在effective_modern_cplusplus.cpp中include <cmath>和<functional>是否起作用，或者检查下C、CXX编译器是否能正常识别

**Comment by HatakeKakaxi** [comment]
好的，我在另一台电脑上面编译成功了，谢谢答复
