### ISSUE TITLE
win11 visual studio 2022 Debug x64版本 编译错误

### ISSUE THREAD

**Issue by FarewellYi** [fengbingchun/Messy_Test#5]

**Comment by FarewellYi** [comment]
问题集中在temple.hpp和operator.hpp中，例如：

>D:\1-Project\Messy_Test-master\demo\CppBaseTest\template.hpp(10,8): error C2676: 二进制“>”:“const T”不定义该运算符或到预定义运算符可接收的类型的转换
1>D:\1-Project\Messy_Test-master\demo\CppBaseTest\template.hpp(21,4): error C2143: 语法错误: 缺少“;”(在“*”的前面)
1>D:\1-Project\Messy_Test-master\demo\CppBaseTest\template.hpp(21,4): error C4430: 缺少类型说明符 - 假定为 int。注意: C++ 不支持默认 int
1>D:\1-Project\Messy_Test-master\demo\CppBaseTest\template.hpp(21,11): error C2238: 意外的标记位于“;”之前
1>D:\1-Project\Messy_Test-master\demo\CppBaseTest\template.hpp(30,9): error C2061: 语法错误: 标识符“Ty”
1>D:\1-Project\Messy_Test-master\demo\CppBaseTest\template.hpp(30,2): error C2535: “ComPtr::ComPtr(void)”: 已经定义或声明成员函数
1>D:\1-Project\Messy_Test-master\demo\CppBaseTest\template.hpp(23,2): message : 参见“ComPtr::ComPtr”的声明
1>D:\1-Project\Messy_Test-master\demo\CppBaseTest\template.hpp(44,4): error C2143: 语法错误: 缺少“;”(在“*”的前面)
1>D:\1-Project\Messy_Test-master\demo\CppBaseTest\template.hpp(44,4): error C4430: 缺少类型说明符 - 假定为 int。注意: C++ 不支持默认 int
1>D:\1-Project\Messy_Test-master\demo\CppBaseTest\template.hpp(44,23): error C2334: “{”的前面有意外标记；跳过明显的函数体
1>D:\1-Project\Messy_Test-master\demo\CppBaseTest\template.hpp(49,11): error C2833: “operator Ty”不是可识别的运算符或类型
1>D:\1-Project\Messy_Test-master\demo\CppBaseTest\template.hpp(49,13): error C2059: 语法错误:“newline”
1>D:\1-Project\Messy_Test-master\demo\CppBaseTest\template.hpp(49,18): error C2334: “{”的前面有意外标记；跳过明显的函数体
1>D:\1-Project\Messy_Test-master\demo\CppBaseTest\template.hpp(53,4): error C2143: 语法错误: 缺少“;”(在“*”的前面)
1>D:\1-Project\Messy_Test-master\demo\CppBaseTest\template.hpp(53,4): error C4430: 缺少类型说明符 - 假定为 int。注意: C++ 不支持默认 int
1>D:\1-Project\Messy_Test-master\demo\CppBaseTest\template.hpp(53,19): error C2334: “{”的前面有意外标记；跳过明显的函数体
1>D:\1-Project\Messy_Test-master\demo\CppBaseTest\template.hpp(57,11): error C2833: “operator Ty”不是可识别的运算符或类型
1>D:\1-Project\Messy_Test-master\demo\CppBaseTest\template.hpp(57,13): error C2059: 语法错误:“newline”
1>D:\1-Project\Messy_Test-master\demo\CppBaseTest\template.hpp(57,19): error C2334: “{”的前面有意外标记；跳过明显的函数体
1>D:\1-Project\Messy_Test-master\demo\CppBaseTest\template.hpp(71,17): error C2061: 语法错误: 标识符“Ty”
1>D:\1-Project\Messy_Test-master\demo\CppBaseTest\template.hpp(24,3): error C2065: “m_ptr”: 未声明的标识符
1>D:\1-Project\Messy_Test-master\demo\CppBaseTest\template.hpp(27,3): error C2065: “m_ptr”: 未声明的标识符
1>D:\1-Project\Messy_Test-master\demo\CppBaseTest\template.hpp(28,17): error C2039: "m_ptr": 不是 "ComPtr" 的成员
1>D:\1-Project\Messy_Test-master\demo\CppBaseTest\template.hpp(18,7): message : 参见“ComPtr”的声明
......

但是转到错误行却没有标记错误，是因为一些基础设置出问题了吗？
我使用的常规参数设置如下：
![image](https://user-images.githubusercontent.com/47736905/225179400-e2cd5b79-9930-48d7-8c76-f149adda9ba3.png)
其他参数没有修改

**Comment by FarewellYi** [comment]
是编码格式的问题：Unix(LF)格式在windows下，vs编译不识别。
解决方案：使用Visual Studio Code打开报错的文件，单击右下角显示的LF，弹出框，选择CRLF，保存。

**Comment by fengbingchun** [comment]
@FarewellYi "但是转到错误行却没有标记错误"，可能是文件格式的问题，在windows下如果文件中有中文，但是此文件不是utf-8 bom的话，有时会有奇怪的编译错误，我将template.hpp的文件格式从utf-8调整为了utf-8 bom，已提交更新，你后面可以试试是否在window11上可正常编译了
